In [1]:
from google.cloud import storage
import os
from io import BytesIO
import pandas as pd

#Connect to GCP bucket and assign the bucket_name and specify the file name
bucket_name = "assignment3-budget" #Assign the bucket name where your file is stored
storage_client = storage.Client()

bucket = storage_client.get_bucket(bucket_name)

In [2]:
blob = storage.blob.Blob("Reviews.csv",bucket)
blob

In [3]:
# Convert to a pandas dataframe
content = blob.download_as_string()
train = pd.read_csv(BytesIO(content))

In [4]:
train

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...,...,...
568449,568450,B001EO7N10,A28KG5XORO54AY,Lettie D. Carter,0,0,5,1299628800,Will not do without,Great for sesame chicken..this is a good if no...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,R. Sawyer,0,0,2,1331251200,disappointed,I'm disappointed with the flavor. The chocolat...
568451,568452,B004I613EE,A121AA1GQV751Z,"pksd ""pk_007""",2,2,5,1329782400,Perfect for our maltipoo,"These stars are small, so you can give 10-15 o..."
568452,568453,B004I613EE,A3IBEVCTXKNOH,"Kathy A. Welch ""katwel""",1,1,5,1331596800,Favorite Training and reward treat,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,srfell17,0,0,5,1338422400,Great Honey,"I am very satisfied ,product is as advertised,..."

In [5]:
# put the userid to a set
userid_set = set(train['UserId'])
productid_set = set(train['ProductId'])

In [6]:
userid_list = list(userid_set)
productid_list = list(productid_set)

In [7]:
# assign numeric id to userid
userid_assign = []
for i in range(len(userid_list)):
    i += 1
    userid_assign.append(i)
userid_assign

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...]

In [8]:
# assign numeric id to productid
productid_assign = []
start_num = 300000
for k in range(len(productid_list)):
    k = k + start_num
    productid_assign.append(k)
productid_assign

[300000,
 300001,
 300002,
 300003,
 300004,
 300005,
 300006,
 300007,
 300008,
 300009,
 300010,
 300011,
 300012,
 300013,
 300014,
 300015,
 300016,
 300017,
 300018,
 300019,
 300020,
 300021,
 300022,
 300023,
 300024,
 300025,
 300026,
 300027,
 300028,
 300029,
 300030,
 300031,
 300032,
 300033,
 300034,
 300035,
 300036,
 300037,
 300038,
 300039,
 300040,
 300041,
 300042,
 300043,
 300044,
 300045,
 300046,
 300047,
 300048,
 300049,
 300050,
 300051,
 300052,
 300053,
 300054,
 300055,
 300056,
 300057,
 300058,
 300059,
 300060,
 300061,
 300062,
 300063,
 300064,
 300065,
 300066,
 300067,
 300068,
 300069,
 300070,
 300071,
 300072,
 300073,
 300074,
 300075,
 300076,
 300077,
 300078,
 300079,
 300080,
 300081,
 300082,
 300083,
 300084,
 300085,
 300086,
 300087,
 300088,
 300089,
 300090,
 300091,
 300092,
 300093,
 300094,
 300095,
 300096,
 300097,
 300098,
 300099,
 300100,
 300101,
 300102,
 300103,
 300104,
 300105,
 300106,
 300107,
 300108,
 300109,
 300110,
 300111,
 300112,
 300113,
 300114,
 300115,
 300116,
 300117,
 300118,
 300119,
 300120,
 300121,
 300122,
 300123,
 300124,
 300125,
 300126,
 300127,
 300128,
 300129,
 300130,
 300131,
 300132,
 300133,
 300134,
 300135,
 300136,
 300137,
 300138,
 300139,
 300140,
 300141,
 300142,
 300143,
 300144,
 300145,
 300146,
 300147,
 300148,
 300149,
 300150,
 300151,
 300152,
 300153,
 300154,
 300155,
 300156,
 300157,
 300158,
 300159,
 300160,
 300161,
 300162,
 300163,
 300164,
 300165,
 300166,
 300167,
 300168,
 300169,
 300170,
 300171,
 300172,
 300173,
 300174,
 300175,
 300176,
 300177,
 300178,
 300179,
 300180,
 300181,
 300182,
 300183,
 300184,
 300185,
 300186,
 300187,
 300188,
 300189,
 300190,
 300191,
 300192,
 300193,
 300194,
 300195,
 300196,
 300197,
 300198,
 300199,
 300200,
 300201,
 300202,
 300203,
 300204,
 300205,
 300206,
 300207,
 300208,
 300209,
 300210,
 300211,
 300212,
 300213,
 300214,
 300215,
 300216,
 300217,
 300218,
 300219,
 300220,
 300221,
 300222,
 300223,
 300224,
 300225,
 300226,
 300227,
 300228,
 300229,
 300230,
 300231,
 300232,
 300233,
 300234,
 300235,
 300236,
 300237,
 300238,
 300239,
 300240,
 300241,
 300242,
 300243,
 300244,
 300245,
 300246,
 300247,
 300248,
 300249,
 300250,
 300251,
 300252,
 300253,
 300254,
 300255,
 300256,
 300257,
 300258,
 300259,
 300260,
 300261,
 300262,
 300263,
 300264,
 300265,
 300266,
 300267,
 300268,
 300269,
 300270,
 300271,
 300272,
 300273,
 300274,
 300275,
 300276,
 300277,
 300278,
 300279,
 300280,
 300281,
 300282,
 300283,
 300284,
 300285,
 300286,
 300287,
 300288,
 300289,
 300290,
 300291,
 300292,
 300293,
 300294,
 300295,
 300296,
 300297,
 300298,
 300299,
 300300,
 300301,
 300302,
 300303,
 300304,
 300305,
 300306,
 300307,
 300308,
 300309,
 300310,
 300311,
 300312,
 300313,
 300314,
 300315,
 300316,
 300317,
 300318,
 300319,
 300320,
 300321,
 300322,
 300323,
 300324,
 300325,
 300326,
 300327,
 300328,
 300329,
 300330,
 300331,
 300332,
 300333,
 300334,
 300335,
 300336,
 300337,
 300338,
 300339,
 300340,
 300341,
 300342,
 300343,
 300344,
 300345,
 300346,
 300347,
 300348,
 300349,
 300350,
 300351,
 300352,
 300353,
 300354,
 300355,
 300356,
 300357,
 300358,
 300359,
 300360,
 300361,
 300362,
 300363,
 300364,
 300365,
 300366,
 300367,
 300368,
 300369,
 300370,
 300371,
 300372,
 300373,
 300374,
 300375,
 300376,
 300377,
 300378,
 300379,
 300380,
 300381,
 300382,
 300383,
 300384,
 300385,
 300386,
 300387,
 300388,
 300389,
 300390,
 300391,
 300392,
 300393,
 300394,
 300395,
 300396,
 300397,
 300398,
 300399,
 300400,
 300401,
 300402,
 300403,
 300404,
 300405,
 300406,
 300407,
 300408,
 300409,
 300410,
 300411,
 300412,
 300413,
 300414,
 300415,
 300416,
 300417,
 300418,
 300419,
 300420,
 300421,
 300422,
 300423,
 300424,
 300425,
 300426,
 300427,
 300428,
 300429,
 300430,
 300431,
 300432,
 300433,
 300434,
 300435,
 300436,
 300437,
 300438,
 300439,
 300440,
 300441,
 300442,
 300443,
 300444,
 300445,
 300446,
 300447,
 300448,
 300449,
 300450,
 300451,
 300452,
 300453,
 300454,
 300455,
 300456,
 300457,
 300458,
 300459,
 300460,
 300461,
 300462,
 300463,
 300464,
 300465,
 300466,
 300467,
 300468,
 300469,
 300470,
 300471,
 300472,
 300473,
 300474,
 300475,
 300476,
 300477,
 300478,
 300479,
 300480,
 300481,
 300482,
 300483,
 300484,
 300485,
 300486,
 300487,
 300488,
 300489,
 300490,
 300491,
 300492,
 300493,
 300494,
 300495,
 300496,
 300497,
 300498,
 300499,
 300500,
 300501,
 300502,
 300503,
 300504,
 300505,
 300506,
 300507,
 300508,
 300509,
 300510,
 300511,
 300512,
 300513,
 300514,
 300515,
 300516,
 300517,
 300518,
 300519,
 300520,
 300521,
 300522,
 300523,
 300524,
 300525,
 300526,
 300527,
 300528,
 300529,
 300530,
 300531,
 300532,
 300533,
 300534,
 300535,
 300536,
 300537,
 300538,
 300539,
 300540,
 300541,
 300542,
 300543,
 300544,
 300545,
 300546,
 300547,
 300548,
 300549,
 300550,
 300551,
 300552,
 300553,
 300554,
 300555,
 300556,
 300557,
 300558,
 300559,
 300560,
 300561,
 300562,
 300563,
 300564,
 300565,
 300566,
 300567,
 300568,
 300569,
 300570,
 300571,
 300572,
 300573,
 300574,
 300575,
 300576,
 300577,
 300578,
 300579,
 300580,
 300581,
 300582,
 300583,
 300584,
 300585,
 300586,
 300587,
 300588,
 300589,
 300590,
 300591,
 300592,
 300593,
 300594,
 300595,
 300596,
 300597,
 300598,
 300599,
 300600,
 300601,
 300602,
 300603,
 300604,
 300605,
 300606,
 300607,
 300608,
 300609,
 300610,
 300611,
 300612,
 300613,
 300614,
 300615,
 300616,
 300617,
 300618,
 300619,
 300620,
 300621,
 300622,
 300623,
 300624,
 300625,
 300626,
 300627,
 300628,
 300629,
 300630,
 300631,
 300632,
 300633,
 300634,
 300635,
 300636,
 300637,
 300638,
 300639,
 300640,
 300641,
 300642,
 300643,
 300644,
 300645,
 300646,
 300647,
 300648,
 300649,
 300650,
 300651,
 300652,
 300653,
 300654,
 300655,
 300656,
 300657,
 300658,
 300659,
 300660,
 300661,
 300662,
 300663,
 300664,
 300665,
 300666,
 300667,
 300668,
 300669,
 300670,
 300671,
 300672,
 300673,
 300674,
 300675,
 300676,
 300677,
 300678,
 300679,
 300680,
 300681,
 300682,
 300683,
 300684,
 300685,
 300686,
 300687,
 300688,
 300689,
 300690,
 300691,
 300692,
 300693,
 300694,
 300695,
 300696,
 300697,
 300698,
 300699,
 300700,
 300701,
 300702,
 300703,
 300704,
 300705,
 300706,
 300707,
 300708,
 300709,
 300710,
 300711,
 300712,
 300713,
 300714,
 300715,
 300716,
 300717,
 300718,
 300719,
 300720,
 300721,
 300722,
 300723,
 300724,
 300725,
 300726,
 300727,
 300728,
 300729,
 300730,
 300731,
 300732,
 300733,
 300734,
 300735,
 300736,
 300737,
 300738,
 300739,
 300740,
 300741,
 300742,
 300743,
 300744,
 300745,
 300746,
 300747,
 300748,
 300749,
 300750,
 300751,
 300752,
 300753,
 300754,
 300755,
 300756,
 300757,
 300758,
 300759,
 300760,
 300761,
 300762,
 300763,
 300764,
 300765,
 300766,
 300767,
 300768,
 300769,
 300770,
 300771,
 300772,
 300773,
 300774,
 300775,
 300776,
 300777,
 300778,
 300779,
 300780,
 300781,
 300782,
 300783,
 300784,
 300785,
 300786,
 300787,
 300788,
 300789,
 300790,
 300791,
 300792,
 300793,
 300794,
 300795,
 300796,
 300797,
 300798,
 300799,
 300800,
 300801,
 300802,
 300803,
 300804,
 300805,
 300806,
 300807,
 300808,
 300809,
 300810,
 300811,
 300812,
 300813,
 300814,
 300815,
 300816,
 300817,
 300818,
 300819,
 300820,
 300821,
 300822,
 300823,
 300824,
 300825,
 300826,
 300827,
 300828,
 300829,
 300830,
 300831,
 300832,
 300833,
 300834,
 300835,
 300836,
 300837,
 300838,
 300839,
 300840,
 300841,
 300842,
 300843,
 300844,
 300845,
 300846,
 300847,
 300848,
 300849,
 300850,
 300851,
 300852,
 300853,
 300854,
 300855,
 300856,
 300857,
 300858,
 300859,
 300860,
 300861,
 300862,
 300863,
 300864,
 300865,
 300866,
 300867,
 300868,
 300869,
 300870,
 300871,
 300872,
 300873,
 300874,
 300875,
 300876,
 300877,
 300878,
 300879,
 300880,
 300881,
 300882,
 300883,
 300884,
 300885,
 300886,
 300887,
 300888,
 300889,
 300890,
 300891,
 300892,
 300893,
 300894,
 300895,
 300896,
 300897,
 300898,
 300899,
 300900,
 300901,
 300902,
 300903,
 300904,
 300905,
 300906,
 300907,
 300908,
 300909,
 300910,
 300911,
 300912,
 300913,
 300914,
 300915,
 300916,
 300917,
 300918,
 300919,
 300920,
 300921,
 300922,
 300923,
 300924,
 300925,
 300926,
 300927,
 300928,
 300929,
 300930,
 300931,
 300932,
 300933,
 300934,
 300935,
 300936,
 300937,
 300938,
 300939,
 300940,
 300941,
 300942,
 300943,
 300944,
 300945,
 300946,
 300947,
 300948,
 300949,
 300950,
 300951,
 300952,
 300953,
 300954,
 300955,
 300956,
 300957,
 300958,
 300959,
 300960,
 300961,
 300962,
 300963,
 300964,
 300965,
 300966,
 300967,
 300968,
 300969,
 300970,
 300971,
 300972,
 300973,
 300974,
 300975,
 300976,
 300977,
 300978,
 300979,
 300980,
 300981,
 300982,
 300983,
 300984,
 300985,
 300986,
 300987,
 300988,
 300989,
 300990,
 300991,
 300992,
 300993,
 300994,
 300995,
 300996,
 300997,
 300998,
 300999,
 ...]

In [9]:
userid_df = pd.DataFrame({'userid_new': userid_assign,
                             'userid_old': userid_list})
userid_df

        userid_new      userid_old
0                1   AF1NQ188YO7A7
1                2  A3B1K0IZK4XE1M
2                3  A2RZI5MA4WDC7D
3                4  A1VHAK409DE0AA
4                5  A1MBC8A72OKKB2
...            ...             ...
256054      256055  A13AI7ZM923X52
256055      256056  A2BL4U089N7E4O
256056      256057  A200NJR1P9CFCX
256057      256058  A3H7AGXM3Z7VQ4
256058      256059  A1D1IHK5SJE8AQ

[256059 rows x 2 columns]

In [10]:
productid_df = pd.DataFrame({'productid_new': productid_assign,
                            'productid_old': productid_list})
productid_df

       productid_new productid_old
0             300000    B001EQ550E
1             300001    B005VH0AXE
2             300002    B001H3PYU0
3             300003    B0033UU19Y
4             300004    B00743W50O
...              ...           ...
74253         374253    B002D300ZC
74254         374254    B004K76JKO
74255         374255    B000AMCA92
74256         374256    B004T3QMD8
74257         374257    B0032GQMB0

[74258 rows x 2 columns]

In [26]:
productid_df['productid_new'][1]

300001

In [11]:
# join dataframe with numeric productid to the raw dataset
kk = train.set_index('ProductId').join(productid_df.set_index('productid_old'))

In [12]:
# join dataftame with numeric userid to the raw dataset
new_data = kk.set_index('UserId').join(userid_df.set_index('userid_old'))
new_data

,Id,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,productid_new,userid_new
#oc-R103C0QSV1DF5E,136323,C,1,2,5,1343088000,Great for the Price,I have to say I was a little apprehensive to b...,344580,119808
#oc-R109MU5OBBZ59U,516062,AayGee,0,1,5,1350086400,AWESOME Coffee!!!!,Received my free K cups as a sample promotion ...,332029,70784
#oc-R10LFEMQEW6QGZ,516079,Julie,0,1,5,1345939200,Brooklyn Bean Roastery Breakfast Blend K-Cups,Brooklyn Bean Roastery Blend K-Cups are great ...,332029,75565
#oc-R10LT57ZGIB140,378693,dipr,0,0,3,1310601600,Some damage,The shipment of the dog food was quick. Howev...,329011,40522
#oc-R10UA029WVWIUI,136545,Kim D,0,0,1,1342483200,Less than satisfactory. I gave the Brooklyn K...,"Brooklyn ""French Roast"" K-Cup Coffee is not on...",344580,38229
...,...,...,...,...,...,...,...,...,...,...
AZZV9PDNMCOZW,422838,"Anne B. Ward ""Dr Anne B""",0,0,4,1329436800,I like it,Even though this mix is not as spicy as I anti...,300285,157872
AZZVNIMTTMJH6,190698,sugarwaif,0,0,5,1268179200,pretty amazing,i've wanted one of these since i saw it in an ...,372503,101905
AZZY649VYAHQS,222781,Worldwide1,1,1,5,1309737600,I Have Spoken.,All of the chocolate arrived with out melting ...,350476,112000
AZZYCJOJLUDYR,131469,"Hazel MccLellan ""H.M.""",0,0,5,1337472000,Amazing flavor!!,I use this all the time! Good for BBQ ing or p...,359429,23378
AZZZOVIBXHGDR,183897,Logan R. Freijo,0,0,2,1333497600,Disappointed,I ordered this cereal based on the good review...,367457,178300

In [13]:
recommendation_train = new_data[['userid_new','productid_new','Score']]

In [14]:
# impport everything we need for the rec sys
from pyspark.sql.types import *
from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.recommendation import ALS
from pyspark.sql import Row
from pyspark.sql import SparkSession

In [15]:
# initialize spark session
spark = SparkSession.builder.appName('Recommendation_system').getOrCreate()

In [16]:
# create a spark dataframe from a pandas dataframe
df = spark.createDataFrame(recommendation_train)

In [17]:
# create testing and training data
(training, test) = df.randomSplit([0.8, 0.2])

In [18]:
als = ALS(maxIter=5, regParam=0.01, userCol="userid_new", itemCol="productid_new", ratingCol="Score",coldStartStrategy="drop")

In [19]:
model = als.fit(training)

In [20]:
# generate predictions and evaluations
predictions = model.transform(test)

In [21]:
evaluator = RegressionEvaluator(metricName="rmse", labelCol="Score",predictionCol="prediction")

In [22]:
rmse = evaluator.evaluate(predictions)
print("Root-mean-square error = " + str(rmse))

Root-mean-square error = 3.6049242610765804

In [58]:
#recommendations
userRecs = model.recommendForAllUsers(10) # top 10 food recommendations for each user
foodRecs = model.recommendForAllItems(10) # top 10 user recommendations for each food
users = df.select(als.getUserCol()).distinct().limit(3) 
userSubsetRecs = model.recommendForUserSubset(users, 10) # top 10 movie recommendations for a specified set of users
food = df.select(als.getItemCol()).distinct().limit(3)
foodSubSetRecs = model.recommendForItemSubset(movies, 10) # top 10 user recommendations for a specified set of food.

In [24]:
# top 10 food recommendations for each user
userRecs.show()

+----------+--------------------+
|userid_new|     recommendations|
+----------+--------------------+
|       148|[[338870, 21.1642...|
|       463|[[340168, 10.0800...|
|       471|[[344163, 5.30399...|
|       496|[[368810, 6.23129...|
|       833|[[306470, 10.9357...|
|      1088|[[331474, 3.99964...|
|      1238|[[343749, 4.99949...|
|      1342|[[343214, 3.28343...|
|      1580|[[331193, 9.27023...|
|      1591|[[309798, 3.12485...|
|      1645|[[307378, 9.26769...|
|      1829|[[371222, 19.5249...|
|      1959|[[347411, 6.82427...|
|      2142|[[342222, 10.0550...|
|      2366|[[335116, 9.32228...|
|      2659|[[322977, 6.32757...|
|      2866|[[327914, 3.03591...|
|      3175|[[362057, 23.2717...|
|      3749|[[308460, 5.08199...|
|      3794|[[358231, 9.85381...|
+----------+--------------------+
only showing top 20 rows

In [59]:
# top 10 user recommendations for each food
foodRecs.show()

+-------------+--------------------+
|productid_new|     recommendations|
+-------------+--------------------+
|       300282|[[182556, 35.1440...|
|       300474|[[69739, 37.88813...|
|       300522|[[157275, 24.8124...|
|       300539|[[58238, 68.99089...|
|       300574|[[158534, 23.1153...|
|       300601|[[70250, 27.31992...|
|       300779|[[63928, 35.06085...|
|       300825|[[198245, 4.38534...|
|       301535|[[138032, 30.4687...|
|       301798|[[33157, 22.52991...|
|       301992|[[243518, 23.2491...|
|       302124|[[131821, 35.1073...|
|       302344|[[231132, 54.4856...|
|       302550|[[25420, 47.36453...|
|       302825|[[199888, 48.2340...|
|       302855|[[218383, 48.4692...|
|       303539|[[254974, 23.3775...|
|       303632|[[35943, 5.593763...|
|       303886|[[229994, 23.4305...|
|       304030|[[214537, 28.0610...|
+-------------+--------------------+
only showing top 20 rows

In [46]:
Recommendation_list = userRecs.toPandas()
Recommendation_list

        userid_new                                    recommendations
0              148  [(338870, 21.16429328918457), (373178, 19.4938...
1              463  [(340168, 10.080034255981445), (371470, 9.8224...
2              471  [(344163, 5.303990840911865), (316212, 5.11763...
3              496  [(368810, 6.231294631958008), (333878, 6.01704...
4              833  [(306470, 10.935750007629395), (318128, 10.206...
...            ...                                                ...
219551      255183  [(339802, 4.874143600463867), (326829, 4.68319...
219552      255277  [(340775, 30.27634620666504), (318128, 28.4284...
219553      255391  [(370344, 10.79914379119873), (337118, 9.90756...
219554      255830  [(339047, 11.823888778686523), (334920, 10.748...
219555      256045  [(318743, 7.525881767272949), (324289, 7.13311...

[219556 rows x 2 columns]

In [39]:
popularity = new_data.groupby('productid_new', as_index = False)['Score'].mean().sort_values(by='Score', ascending=False)

In [40]:
popularity

       productid_new  Score
74257         374257    5.0
27450         327450    5.0
57458         357458    5.0
27443         327443    5.0
27444         327444    5.0
...              ...    ...
20475         320475    1.0
69788         369788    1.0
33717         333717    1.0
15104         315104    1.0
37129         337129    1.0

[74258 rows x 2 columns]

In [43]:
top_food = popularity['productid_new'].tolist()[:10]

In [44]:
top_food

[374257,
 327450,
 357458,
 327443,
 327444,
 327446,
 327448,
 357457,
 357456,
 327438]

In [51]:
Recommendation_list['recommendations'][0][0][0]

338870

In [53]:
overlap = []
for i in range(219556):
    k = 0
    for j in range(10):
        if Recommendation_list['recommendations'][i][j][0] in top_food:
            k+=1
    overlap.append(k/10)

In [54]:
overlap

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [55]:
Recommendation_list['overlap'] = overlap

In [56]:
Recommendation_list

        userid_new                                    recommendations  overlap
0              148  [(338870, 21.16429328918457), (373178, 19.4938...      0.0
1              463  [(340168, 10.080034255981445), (371470, 9.8224...      0.0
2              471  [(344163, 5.303990840911865), (316212, 5.11763...      0.0
3              496  [(368810, 6.231294631958008), (333878, 6.01704...      0.0
4              833  [(306470, 10.935750007629395), (318128, 10.206...      0.0
...            ...                                                ...      ...
219551      255183  [(339802, 4.874143600463867), (326829, 4.68319...      0.0
219552      255277  [(340775, 30.27634620666504), (318128, 28.4284...      0.0
219553      255391  [(370344, 10.79914379119873), (337118, 9.90756...      0.0
219554      255830  [(339047, 11.823888778686523), (334920, 10.748...      0.0
219555      256045  [(318743, 7.525881767272949), (324289, 7.13311...      0.0

[219556 rows x 3 columns]

In [57]:
Recommendation_list.to_csv("Food_Recommendation.csv")